### PR TITLE
fix check os type for linux and dataPath directory

### LINKED ISSUE #9: error saving settings in root directory
Hi,
I've installed saaghar v3 in my arch linux os from aur.
When i closing the app or changing anything in settings, the app will raise an error that can't save `/settings.ini` and as it shows, it's trying to save settings data in root directory and has no permission to that.
I also compiled the app from the source code and this problem was still happened.

image

### PR DESCRIPTION
**Pull request by AmirAref**
Fixes #9

### CODE REVIEW

File: src/saagharapplication.cpp [hunk 1]
```diff
@@ -236,8 +236,8 @@ void SaagharApplication::setupPaths()
         resourcesPath = QCoreApplication::applicationDirPath();
         dataPath = QDir::homePath() + "/Pozh/Saaghar/";
 #endif
-#ifdef Q_OS_X11
-        resourcesPath = PREFIX"/share/saaghar/";
+#ifdef Q_OS_LINUX
+        resourcesPath = "/usr/share/saaghar/";
```
Comment (srazi) [inline src/saagharapplication.cpp:240]: Thanks, but we don't need to change this line since PREFIX is defined in pro file. The real issue is that Q_OS_X11 is not defined on Arch. Also, I afraid that replacing Q_OS_X11 by Q_OS_X11 create the same bug on other OSes that Saaghar has been ported (e.g. FreeBSD). So, please replace it by: `#if defined(Q_OS_UNIX) && !defined(Q_OS_DARWIN)`

Comment (AmirAref) [reply src/saagharapplication.cpp]: You're right, now it has been updated !
